### ISSUE TITLE
Example shows returning a pointer to db.User but resolver wants a plain db.User

### ISSUE THREAD

**Issue by alaister** [99designs/gqlgen-workshop#1]
Hi,
In your example you show the `User` resolver returning `(*db.User, error)` but my editor is telling me it wants `(db.User, error)` as the return type?

Full function head:
```
func (r *queryResolver) User(ctx context.Context, id string) (*db.User, error) {
```

**Comment by mathewbyrne** [comment]
Check your schema, it should look like:

```
type Query {
    user(id: ID!): User
}

type User {
    id: ID!
    name: String!
}
```

The key is that the root `user` node should be nullable.  Currently `gqlgen` will map nullable GraphQL types to pointers, allowing you to return `nil` from your resolver.  If you don't have a pointer, then you probably have a non-nullable type in the schema.
